### ISSUE TITLE
Regarding the image path link while running the file

### ISSUE THREAD

**Issue by AbhishekMankame** [casual-healthcare/braindiagnose#1]
I came across this GitHub repository and while running the file, as mentioned in the read me file I ran the execution code but I have received the index error

**Comment by azh412** [comment]
Hello Abhishek,

Can you please paste the error you're getting, so I can better understand what's wrong?

Thank you!

**Comment by AbhishekMankame** [comment]
Here I am facing Index error

![Screenshot (5696)](https://user-images.githubusercontent.com/61981517/230267663-bb2fa1ef-f870-4307-8b59-5b6b0ff7ddcd.png)

**Comment by azh412** [comment]
Hello,

Thank you for catching this error. I made a mistake while creating the documentation.

`braindiagnosis.py` is intended to be used with an `input` folder, where images will be fed in, and an `output` folder, where images will go when evaluated. Afterward, you would specify the input and output folder as command line arguments, in that order.

The following is an example command:

```
python braindiagnosis.py [MODEL] [INPUT] [OUTPUT]
```

Thanks!

-azh
